version: "3.9"

services:
  web:
    image: python:3-alpine
    working_dir: /app
    command: python3 -m http.server 5500 --directory /app
    ports:
      - "5500:5500"
    volumes:
      - ./:/app     # Live-edit: host folder synced with container
